# Generated by Django 5.2.5 on 2025-08-25 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shape_App', '0004_remove_address_street_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='Shape_App.tbl_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='Shape_App.tbl_signup')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
