# Generated by Django 5.2.5 on 2025-08-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shape_App', '0007_remove_tbl_product_color_remove_tbl_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
        migrations.AddField(
            model_name='tbl_product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
