# Generated by Django 5.2.5 on 2025-08-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shape_App', '0008_remove_productvariant_image_tbl_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cart',
            name='selected_color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_cart',
            name='selected_size',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
