# Generated by Django 5.2.5 on 2025-11-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shape_App', '0009_tbl_cart_selected_color_tbl_cart_selected_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='video',
            field=models.FileField(null=True, upload_to='Videos/'),
        ),
    ]
